### PR TITLE
Build and dependency updates (use Auto Config from Cloth Config)

### PR DESCRIPTION
**Pull request by Fourmisain**
- use Auto Config from Cloth Config instead of Auto Config Updated
Auto Config has been merged into Cloth Config for quite a while and the original and "Updated" version won't be updated anymore
(The build was already linking to Cloth Config too, except it was using the wrong identifier)
- update to gradle 7.1.1 and update wrapper files
This makes the diff look terrible, all I did was update `gradle-wrapper.properties` and run `gradlew wrapper`
- set `remap = false` for non-obfuscated method mixins
This eliminates some build warnings (sadly not for intermediary method names like lambdas)
- remove deprecated jcenter()
- use withSourcesJar() java plugin task

Tested working on 1.17 and 1.17.1

### CODE REVIEW

**Comment by Fourmisain** [comment]
Ah, I saw you merged it with https://github.com/vlad2305m/Sound-Physics/commit/20f14409ad44a30c7de9a02154277a93ce9be1c2, time to close this!

**Comment by vlad2305m** [comment]
Thank you. I spotted it too late, so I merged it by hand (Where did nice "resolve conflicts" interface go). I don't like when authors don't update their old wiki when they drop a project exacly for this reason.

**Comment by vlad2305m** [comment]
:)

**Comment by Fourmisain** [comment]
You're welcome!
Btw, you should probably update the mod description on CurseForge, because right now it says it needs Cloth Config _and_ Auto Config, but it only needs the former.
(Well okay, the 1.17 version needs Auto Config instead, so maybe specify that 😄)

**Pull request closed without merging**
